repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
        exclude: '.bumpversion.cfg'
    -   id: detect-aws-credentials
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
    -   id: double-quote-string-fixer
-   repo: git://github.com/pre-commit/mirrors-yapf
    rev: 'master'
    hooks:
    -   id: yapf
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    rev: master
    hooks:
    -   id: python-import-sorter
        args: ['--silent-overwrite']
