name: format python code with `black`

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: get the code
      # Instead of using the built-in "checkout" action, we have to do this manually so
      # that we actually check out the *branch* and not just a detached HEAD. This is
      # so we can push back to that branch later.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        REPO_FULLNAME=$(jq -r ".repository.full_name" "$GITHUB_EVENT_PATH")
        echo "## Initializing git repo..."
        git init
        echo "### Adding git remote..."
        git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/$REPO_FULLNAME.git
        echo "### git fetch..."
        git fetch --all
        echo "### Setting branch"
        BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH")
        echo "### Branch: $BRANCH"
        git checkout $BRANCH

    - name: auto-format with black
      run: |
        set -e
        pip install black
        # TODO: figure out how to only run this on .py files that have changed IN the PR
        echo "### Figuring out modified .py files"
        BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH")
        BASE=$(jq -r ".pull_request.base.ref" "$GITHUB_EVENT_PATH")
        echo "## Fetching $BASE"
        git fetch origin $BASE
        echo "Branch is $BRANCH"
        echo "Base is $BASE"
        echo "git branch:"
        git branch
        echo "Let's try merge-base:"
        git merge-base $BRANCH $BASE
        echo "and now git diff"
        git diff --name-only $BRANCH $(git merge-base $BRANCH $BASE)
        MODIFIED_FILES=$(git diff --name-only $BRANCH $(git merge-base $BRANCH $BASE))
        echo "modified files are $MODIFIED_FILES"
        black --target-version=py27 $MODIFIED_FILES

    - name: commit changes back to PR
      run: |
        set -e
        git config user.email '227068+radix@users.noreply.github.com'
        git config user.name "radix's formatting bot"
        git add .
        git commit -m 'auto-format Python code'
        # Apparently github has some sort of loop-detection,
        # so it won't recursively run this workflow when this
        # is pushed, fortunately!
        git push
